const {
    fourOne,
    fourTwo,
    fourThree,
    fourFour,
    fourFive,
    fourSix,
    fourSeven,
    fourEight,
    fourNine,
    fourTen,
    fourEleven,
    fourTwelve,
    fourThirteen,
    fourFourteen,
    fourFifteen,
    fourSixteen,
    fourSeventeen,
    fourEighteen,
  } = require("./handleFourPerson");